config/routes.rb
Rails.application.routes.draw do
  root to: 'barangs#barang'

  resources :barangs
  resources :merks
  resources :kategoris

end

app/models/barang.rb
class Barang < ActiveRecord::Base
  belongs_to :merk
  belongs_to :kategori
  validates :nama, presence: true, uniqueness: { case_sensitive: false }

  mount_uploader :gambar, GambarUploader
end

app/models/kategori.rb
class Kategori < ActiveRecord::Base
  belongs_to :barang
  has_many :barang

  validates :nama, presence: true, uniqueness: { case_sensitive: false }
end

app/models/merk.rb
class Merk < ActiveRecord::Base
  belongs_to :barang
  has_many :barang

  validates :nama, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/barangs_controller.rb
 class BarangsController < ApplicationController
  before_action :set_barang, only: [:show, :edit, :update, :destroy]

  # GET /barangs
  # GET /barangs.json
  def index
    @barangs = Barang.all
    @kategoris = Kategori.all
    @merks = Merk.all
  end

  # GET /barangs/1
  # GET /barangs/1.json
  def show
    @merks = Merk.all
    @kategoris = Kategori.all
  end

  def barang
    @barangs = Barang.all
  end

  # GET /barangs/new
  def new
    @barang = Barang.new
    @kategoris = Kategori.all
    @merks = Merk.all
  end

  # GET /barangs/1/edit
  def edit
    @merks = Merk.all
    @kategoris = Kategori.all
  end

  # POST /barangs
  # POST /barangs.json
  def create
    @barang = Barang.new(barang_params)

    respond_to do |format|
      if @barang.save
        format.html { redirect_to @barang, notice: 'Barang berhasil ditambah' }
        format.json { render :show, status: :created, location: @barang }
      else
        format.html { render :new }
        format.json { render json: @barang.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /barangs/1
  # PATCH/PUT /barangs/1.json
  def update
    respond_to do |format|
      if @barang.update(barang_params)
        format.html { redirect_to @barang, notice: 'Barang berhasil diedit' }
        format.json { render :show, status: :ok, location: @barang }
      else
        format.html { render :edit }
        format.json { render json: @barang.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /barangs/1
  # DELETE /barangs/1.json
  def destroy
    @barang.destroy
    respond_to do |format|
      format.html { redirect_to barangs_url, notice: 'Barang berhasil dihapus' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_barang
      @barang = Barang.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def barang_params
      params.require(:barang).permit(:kategori_id, :merk_id, :nama, :baik, :rusak, :masuk, :gambar, :keterangan)
    end
end

app/controllers/kategoris_controller.rb
class KategorisController < ApplicationController
  before_action :set_kategori, only: [:show, :edit, :update, :destroy]

  # GET /kategoris
  # GET /kategoris.json
  def index
    @kategoris = Kategori.all
  end

  # GET /kategoris/1
  # GET /kategoris/1.json
  def show
  end

  # GET /kategoris/new
  def new
    @kategori = Kategori.new
  end

  # GET /kategoris/1/edit
  def edit
  end

  # POST /kategoris
  # POST /kategoris.json
  def create
    @kategori = Kategori.new(kategori_params)

    respond_to do |format|
      if @kategori.save
        format.html { redirect_to @kategori, notice: 'Kategori berhasil dibuat' }
        format.json { render :show, status: :created, location: @kategori }
      else
        format.html { render :new }
        format.json { render json: @kategori.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kategoris/1
  # PATCH/PUT /kategoris/1.json
  def update
    respond_to do |format|
      if @kategori.update(kategori_params)
        format.html { redirect_to @kategori, notice: 'Kategori berhasil diedit' }
        format.json { render :show, status: :ok, location: @kategori }
      else
        format.html { render :edit }
        format.json { render json: @kategori.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kategoris/1
  # DELETE /kategoris/1.json
  def destroy
    @kategori.destroy
    respond_to do |format|
      format.html { redirect_to kategoris_url, notice: 'Kategori berhasil dihapus' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kategori
      @kategori = Kategori.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kategori_params
      params.require(:kategori).permit(:nama)
    end
end

app/controllers/merks_controller.rb
class MerksController < ApplicationController
  before_action :set_merk, only: [:show, :edit, :update, :destroy]

  # GET /merks
  # GET /merks.json
  def index
    @merks = Merk.all
  end

  # GET /merks/1
  # GET /merks/1.json
  def show
  end

  # GET /merks/new
  def new
    @merk = Merk.new
  end

  # GET /merks/1/edit
  def edit
  end

  # POST /merks
  # POST /merks.json
  def create
    @merk = Merk.new(merk_params)

    respond_to do |format|
      if @merk.save
        format.html { redirect_to @merk, notice: 'Merk berhasil ditambah.' }
        format.json { render :show, status: :created, location: @merk }
      else
        format.html { render :new }
        format.json { render json: @merk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /merks/1
  # PATCH/PUT /merks/1.json
  def update
    respond_to do |format|
      if @merk.update(merk_params)
        format.html { redirect_to @merk, notice: 'Merk berhasil diedit' }
        format.json { render :show, status: :ok, location: @merk }
      else
        format.html { render :edit }
        format.json { render json: @merk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merks/1
  # DELETE /merks/1.json
  def destroy
    @merk.destroy
    respond_to do |format|
      format.html { redirect_to merks_url, notice: 'Merk berhasil dihapus' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merk
      @merk = Merk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def merk_params
      params.require(:merk).permit(:kategori_id, :nama)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/barangs_helper.rb
module BarangsHelper
end

app/helpers/kategoris_helper.rb
module KategorisHelper
end

app/helpers/merks_helper.rb
module MerksHelper
end

app/views/barangs/_form.html.erb
<%= form_for(@barang) do |f| %>
  <% if @barang.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@barang.errors.count, "error") %> prohibited this barang from being saved:</h2>

      <ul>
      <% @barang.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
    <div class="field">
      <%= f.label :nama %><br>
      <%= f.text_field :nama, class: 'form-control'%>
    </div><br>
    <div class="field">
      <%= f.label :pilih_kategori %><br>
      <%= f.collection_select(:kategori_id, @kategoris, :id, :nama, {prompt: "pilih kategori"}, class: 'form-control') %>
    </div><br>
    <div class="field">
      <%= f.label :pilih_merk %><br>
      <%= f.collection_select(:merk_id, @merks, :id, :nama, {prompt: "pilih merk"}, class: 'form-control') %>
    </div><br>

    <fieldset>
    <legend>Jumlah :</legend>
    <div class="field">
      <%= f.label :baik %><br>
      <%= f.number_field :baik, class: 'form-control'%>
    </div>
    <div class="field">
      <%= f.label :rusak %><br>
      <%= f.number_field :rusak, class: 'form-control' %>
    </div>
    </fieldset><br/>

    <div class="field">
      <%= f.label :masuk %><br>
      <%= f.date_select :masuk, class: 'form-control' %>
    </div><br>
    <div class="field">
      <%= f.label :gambar %><br>
      <%= f.file_field :gambar, class: 'form-control' %>
    </div><br>
    <div class="field">
      <%= f.label :keterangan %><br>
      <%= f.text_area :keterangan, class: 'form-control' %>
    </div><br>
    <div class="actions">
      <%= f.submit "simpan", class: 'btn btn-primary'%>
      <%= link_to 'kembali', barangs_path, class: 'btn btn-primary'%> 
    </div>
    </div>
  </div>
<% end %>

app/views/barangs/barang.html.erb
<script language="javascript" type="text/javascript">
  function printDiv(divID) {
      //Get the HTML of div
      var divElements = document.getElementById(divID).innerHTML;
      //Get the HTML of whole page
      var oldPage = document.body.innerHTML;

      //Reset the page's HTML with div's HTML only
      document.body.innerHTML = 
        "<html><head><title></title></head><body>" + 
        divElements + "</body>";

      //Print Page
      window.print();

      //Restore orignal HTML
      document.body.innerHTML = oldPage;
  }
</script>

<div id="printablediv">
<h1>Data Barang</h1>

<table class="table css-serial table-striped">
  <thead>
    <tr>
      <th rowspan="2">No</th>
      <th rowspan="2">Nama</th>
      <th colspan="2">Kondisi</th>
      <th rowspan="2">Jumlah</th>
      <th rowspan="2">Keterangan</th>
    </tr>
    <tr>
      <th>Baik</th>
      <th>Rusak</th>
    </tr>
  </thead>

  <tbody>
    <% @barangs.each do |barang| %>
      <tr>
        <td></td>
        <td><%= barang.nama %></td>
        <td><%= barang.baik %></td>
        <td><%= barang.rusak %></td>
        <td><%= barang.baik+barang.rusak %></td>
        <td><%= barang.keterangan %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
      <tr>
        <th colspan="2">Total</th>
        <th><%= Barang.sum(:baik) %></th>
        <th><%= Barang.sum(:rusak) %></th>
        <th colspan="3"></th>
      </tr>
  </tfoot>
</table>
</div>

<input type="button" value="Cetak Data" onclick="javascript:printDiv('printablediv')" class="btn btn-primary"/>
<!-- Barang.count(:group => :kategori_id) -->

app/views/barangs/edit.html.erb
<h1>Edit Barang</h1>

<%= render 'form' %>

app/views/barangs/index.html.erb
<h1>Barang</h1>

<table class="table css-serial table-striped">
  <thead>
    <tr>
      <th rowspan="2">No</th>
      <th rowspan="2">kategori</th>
      <th rowspan="2">Merk</th>
      <th rowspan="2">Nama</th>
      <th colspan="2">Jumlah</th>
      <th rowspan="2">Masuk</th>
      <th rowspan="2">Gambar</th>
      <th rowspan="2">Keterangan</th>
      <th rowspan="2">Pilihan</th>
    </tr>
    <tr>
      <th>Baik</th>
      <th>Rusak</th>
    </tr>
  </thead>

  <tbody>
    <% @barangs.each do |barang| %>
      <tr>
        <td></td>
        <td><%= link_to barang.nama, barang %></td>
        <td><%= barang.merk.nama %></td>
        <td><%= barang.nama %></td>
        <td><%= barang.baik %></td>
        <td><%= barang.rusak %></td>
        <td><%= barang.masuk %></td>
        <td><%= barang.gambar %></td>
        <td><%= barang.keterangan %></td>
        <td><%= link_to '', edit_barang_path(barang), :class=> "glyphicon glyphicon-edit" %> | <%= link_to '', barang, :class=> "glyphicon glyphicon-trash", method: :delete, data: { confirm: 'Hapus Data Ini?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Tambah Barang', new_barang_path, class: "btn btn-primary" %>

app/views/barangs/new.html.erb
<h1>Tambah Barang</h1>

<%= render 'form' %>

app/views/barangs/show.html.erb
<p>
  <strong>Merk:</strong>
  <%= @barang.merk.nama %>
</p>

<p>
  <strong>Nama:</strong>
  <%= @barang.nama %>
</p>

<p>
  <strong>Baik:</strong>
  <%= @barang.baik %>
</p>

<p>
  <strong>Rusak:</strong>
  <%= @barang.rusak %>
</p>

<p>
  <strong>Masuk:</strong>
  <%= @barang.masuk %>
</p>

<p>
  <strong>Gambar:</strong>
  <%= @barang.gambar %>
</p>

<p>
  <strong>Keterangan:</strong>
  <%= @barang.keterangan %>
</p>

<%= link_to 'Edit', edit_barang_path(@barang) %> |
<%= link_to 'Kembali', barangs_path %>

app/views/kategoris/_form.html.erb
<%= form_for(@kategori) do |f| %>
  <% if @kategori.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kategori.errors.count, "error") %> prohibited this kategori from being saved:</h2>

      <ul>
      <% @kategori.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
    <div class="field">
      <%= f.label :nama %>
      <%= f.text_field :nama, class: 'form-control'%>
    </div><br>
    <div class="actions">
      <%= f.submit "simpan", class: 'btn btn-primary'%>
      <%= link_to 'kembali', kategoris_path, class: 'btn btn-primary'%> 
    </div>
    <% end %>

app/views/kategoris/edit.html.erb
<h1>Edit Kategori</h1>

<%= render 'form' %>

<%= link_to 'Show', @kategori %> |
<%= link_to 'Back', kategoris_path %>

app/views/kategoris/index.html.erb
<h1>Kategori</h1>

<table class="table css-serial table-striped">
  <thead>
    <tr>
      <th>No</th>
      <th>Nama</th>
      <th colspan="3">Pilihan</th>
    </tr>
  </thead>

  <tbody>
    <% @kategoris.each do |kategori| %>
      <tr>
        <td></td>
        <td><%= kategori.nama %></td>
        <td><%= link_to '', kategori, :class=> "glyphicon glyphicon-eye-open" %> | <%= link_to '', edit_kategori_path(kategori), :class=> "glyphicon glyphicon-edit" %> | <%= link_to '', kategori, :class=> "glyphicon glyphicon-trash", method: :delete, data: { confirm: 'Hapus Data Ini?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Tambah Kategori', new_kategori_path, class: "btn btn-primary" %>

app/views/kategoris/new.html.erb
<h1>Tambah Kategori</h1>

<%= render 'form' %>

app/views/kategoris/show.html.erb
<p>
  <strong>Nama:</strong>
  <%= @kategori.nama %>
</p>

<%= link_to 'Edit', edit_kategori_path(@kategori) %> |
<%= link_to 'kembali', kategoris_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default id="navigasi" ">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#" style="color: white;">Sistem Inventaris Lab Komputer</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= root_path %>" style="color: white;">Beranda</a></li>
        <li><a href="<%= barangs_path %>" style="color: white;">Barang</a></li>
        <li><a href="<%= kategoris_path %>" style="color: white;">Kategori</a></li>
        <li><a href="<%= merks_path %>" style="color: white;">Merk</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistem Inventaris</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'https://js.stripe.com/v2/' %>

    <%= csrf_meta_tags %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  <nav>
  	<%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
  </nav>
  <div class="container">
    <%= yield %>
  <footer class="footer">
    <div><small>
      <a href="http://www.umbjm.ac.id/">SILK (Sistem Inventaris Lab Kom) &copy; 2016-2017</a></small>
    </div>
  </footer> 
  </div>
  </body>
</html>

app/views/merks/_form.html.erb
<%= form_for(@merk) do |f| %>
  <% if @merk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@merk.errors.count, "error") %> prohibited this merk from being saved:</h2>

      <ul>
      <% @merk.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
    <div class="field">
      <%= f.label :nama %> :
      <%= f.text_field :nama, class: 'form-control'%>
    </div><br>
    <div class="actions">
      <%= f.submit "simpan", class: 'btn btn-primary'%>
      <%= link_to 'kembali', merks_path, class: 'btn btn-primary'%> 
    </div>
    <% end %>

app/views/merks/edit.html.erb
<h1>Edit Merk</h1>

<%= render 'form' %>

app/views/merks/index.html.erb
<h1>Merk</h1>

<table class="table css-serial table-striped">
  <thead>
    <tr>
      <th>No</th>
      <th>Merk</th>
      <th colspan="3">Pilihan</th>
    </tr>
  </thead>

  <tbody>
    <% @merks.each do |merk| %>
      <tr>
        <td></td>
        <td><%= merk.nama %></td>
        <td><%= link_to '', merk, :class=> "glyphicon glyphicon-eye-open" %> | <%= link_to '', edit_merk_path(merk), :class=> "glyphicon glyphicon-edit" %> | <%= link_to '', merk, :class=> "glyphicon glyphicon-trash", method: :delete, data: { confirm: 'Hapus Data Ini?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Tambah Merk', new_merk_path, class: "btn btn-primary" %>

app/views/merks/new.html.erb
<h1>Tambah Merk</h1>

<%= render 'form' %>

app/views/merks/show.html.erb
<p>
  <strong>Nama:</strong>
  <%= @merk.nama %>
</p>

<%= link_to 'Edit', edit_merk_path(@merk) %> |
<%= link_to 'kembali', merks_path %>